#!/usr/bin/env bash

# Install binaries via Cabal in an isolated environment.

self=`basename $0`
if [ $# -eq 0 ]
then
      echo "Usage: $self package(s)"
      exit 1
fi

tmp=`mktemp -d` &&
echo -n "Created temporary directory" &&
cd $tmp &&
echo -n " $tmp"

echo

{
      cabal sandbox init \
      &&
      cabal install --disable-documentation \
                    --disable-library-profiling \
                    --disable-shared \
                    --disable-executable-dynamic \
                    $@ \
      &&
      mv -i --target-directory=$HOME/.cabal/bin \
            .cabal-sandbox/bin/*
} || {
      echo "$self $@: Installation failed!"
}

rm -r $tmp && echo "Removed temporary directory $tmp"
