#!/usr/bin/env bash

# Install binaries via Cabal in an isolated environment.

set -e # Exit if an error occurs

if [ $# -eq 0 ]
then
      self=`basename $0`
      echo "Usage: $self package(s)"
      exit 1
fi

tmp=`mktemp -d`
cd $tmp
cabal sandbox init
cabal install --disable-documentation --disable-library-profiling --disable-shared --disable-executable-dynamic $@
mv -i --target-directory=$HOME/.cabal/bin .cabal-sandbox/bin/*
rm -r $tmp
