#!/bin/sh

# Install binaries via Cabal in an isolated environment.

self="$(basename "$0")"
if [ $# -eq 0 ]
then
      printf "Usage: %s package(s)\n" "$self" >&2
      exit 1
fi

tmp="$(mktemp -d)" &&
printf "Created temporary directory" &&
cd "$tmp" &&
printf " %s\n" "$tmp"

{
      cabal sandbox init \
      &&
      cabal install --disable-documentation \
                    --disable-library-profiling \
                    --disable-shared \
                    --disable-executable-dynamic \
                    "$@" \
      &&
      mv -i --target-directory="$HOME/.cabal/bin" \
            .cabal-sandbox/bin/*
} || {
      printf "%s %s: Installation failed!\n" "$self" "$@" >&2
}

rm -r "$tmp" && printf "Removed temporary directory %s\n" "$tmp"
